version: '3.3'
services:
  elasticsearch:
    image: elasticsearch:2.4.2
    ports:
     - "9300:9300"
     - "9200:9200"
    environment:
     - "discovery.type=single-node"
  cmdelasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
    ports:
      # Set alternative ports to prevent port clash.
      - 10300:9300
      - 10200:9200
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  elasticsearchseven:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    ports:
      # Set alternative ports to prevent port clash.
      - 11300:9300
      - 11200:9200
    environment:
      - "discovery.type=single-node"
  highcharts:
    image: onsdigital/highcharts-export-node
    ports:
     - "9999:8080"
  postgres:
    build: ./postgres
    environment: 
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=mysecretpassword
    ports:
     - "5432:5432"
  mongodb:
    image: mongo:3.6
    ports:
      - 27017:27017
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-1.0.2
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  mathjax:
    image: onsdigital/mathjax-api
    ports:
      - "8888:8080"
  redis:
    image: redis:6
    command: redis-server --requirepass default
    ports:
      - "6379:6379"
