version: '3.3'
services:
  babbage:
    build:
      context: ${ROOT_BABBAGE:-../../../../babbage}
      dockerfile: Dockerfile.local
    expose:
      - "8080"
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      JAVA_OPTS:                " -Xmx512m -Xdebug -Xrunjdwp:transport=dt_socket,address=8010,server=y,suspend=n"
      RESTOLINO_STATIC:         "target/web"
      RESTOLINO_CLASSES:        "target/classes"
      PACKAGE_PREFIX:           "com.github.onsdigital"
      DP_COLOURED_LOGGING:      "true"
      DP_LOGGING_FORMAT:        "pretty_json"
      DEV_ENVIRONMENT:          "Y"
      IS_PUBLISHING:            "Y"
      RELOAD_TEMPLATES:         "Y"
      TEMPLATES_DIR_KEY:        "target/web/templates/handlebars"
      ENABLE_COVID19_FEATURE:   "false"
      CONTENT_SERVICE_URL:      ${ZEBEDEE_URL:-http://zebedee:8082}
      HIGHCHARTS_EXPORT_SERVER: ${HIGHCHARTS_EXPORT_SERVER:-http://highcharts:9999/}
      ELASTIC_SEARCH_SERVER:    ${ELASTIC_SEARCH_SERVER:-localhost}
      ELASTIC_SEARCH_PORT:      ${ELASTIC_SEARCH_PORT:-9300}
      MAP_RENDERER_HOST:        ${MAP_RENDERER_HOST:-http://localhost:23500}
      TABLE_RENDERER_HOST:      ${TABLE_RENDERER_HOST:-http://localhost:23300}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: 10s
      retries: 10
