version: "3.3"
services:
  dp-dimension-importer:
    build:
      context: ${ROOT_IMAGE_API:-../../../../dp-dimension-importer}
      dockerfile: Dockerfile.local
    command:
      - reflex
      - -d
      - none
      - -c
      - ./reflex
    volumes:
      - ${ROOT_IMAGE_API:-../../../../dp-dimension-importer}:/dp-dimension-importer
    expose:
      - "21500"
    ports:
      - 21500:21500
    restart: unless-stopped
    environment:
      BIND_ADDR:                   ":21500"
      DATASET_API_ADDR:            ${DATASET_API_ADDR:-http://dp-dataset-api:22000}
      MONGODB_BIND_ADDR:           ${MONGODB_BIND_ADDR:-mongodb:27017}
      KAFKA_ADDR:                  ${KAFKA_ADDR:-kafka-1:19092,kafka-2:19092,kafka-3:19092}
      KAFKA_MAX_BYTES:             ${KAFKA_MAX_BYTES:-2000000}
      KAFKA_VERSION:               ${KAFKA_VERSION:-3.1.0}
      IS_PUBLISHING:               ${IS_PUBLISHING:-true}
      ZEBEDEE_URL:                 ${ZEBEDEE_URL:-http://zebedee:8082}
      VAULT_ADDR:                  ${VAULT_ADDR:-http://vault:8200}
      NEPTUNE_TLS_SKIP_VERIFY:     ${NEPTUNE_TLS_SKIP_VERIFY:-true}
      GRAPH_ADDR:                  ${GRAPH_ADDR:-wss://host.docker.internal:8182/gremlin}
      GRAPH_DRIVER_TYPE:           ${GRAPH_DRIVER_TYPE:-neptune}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:21500/health" ]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: 10s
      retries: 10
