version: "3.3"
services:
  dp-dimension-search-builder:
    build:
      context: ${ROOT_IMAGE_API:-../../../../dp-dimension-search-builder}
      dockerfile: Dockerfile.local
    command:
      - reflex
      - -d
      - none
      - -c
      - ./reflex
    volumes:
      - ${ROOT_IMAGE_API:-../../../../dp-dimension-search-builder}:/dp-dimension-search-builder
    expose:
      - "22900"
    ports:
      - 22900:22900
    restart: unless-stopped
    environment:
      BIND_ADDR:                   ":22900"
      MONGODB_BIND_ADDR:           ${MONGODB_BIND_ADDR:-mongodb:27017}
      KAFKA_ADDR:                  ${KAFKA_ADDR:-kafka-1:19092,kafka-2:19092,kafka-3:19092}
      KAFKA_MAX_BYTES:             ${KAFKA_MAX_BYTES:-2000000}
      KAFKA_VERSION:               ${KAFKA_VERSION:-3.1.0}
      IS_PUBLISHING:               ${IS_PUBLISHING:-true}
      ZEBEDEE_URL:                 ${ZEBEDEE_URL:-http://zebedee:8082}
      VAULT_ADDR:                  ${VAULT_ADDR:-http://vault:8200}
      HIERARCHY_API_URL:           ${HIERARCHY_API_URL:-http://dp-hierarchy-api:22600}
      ELASTIC_SEARCH_URL:          ${ELASTIC_SEARCH_URL:-http://cmdelasticsearch:9200}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:22900/health" ]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: 10s
      retries: 10
